const lawyersData = [
  {
    id: 1,
    name: "Adv. Rajesh Kumar",
    barRegistrationNo: "KBA/2005/1234",
    specialization: ["Criminal Law", "Constitutional Law"],
    experience: 18,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98450 12345",
    email: "rajesh.kumar@kbalaw.in",
    address: "123, MG Road, Bangalore - 560001",
    languages: ["English", "Kannada", "Hindi"],
    education: "LLB, LLM (Criminal Law)",
    description: "Specialized in criminal defense and constitutional matters with extensive experience in High Court and Supreme Court cases."
  },
  {
    id: 2,
    name: "Adv. Priya Sharma",
    barRegistrationNo: "KBA/2010/5678",
    specialization: ["Civil Law", "Property Law"],
    experience: 13,
    location: "Bangalore",
    court: "Civil Court, Bangalore",
    phone: "+91 98451 23456",
    email: "priya.sharma@kbalaw.in",
    address: "45, Brigade Road, Bangalore - 560025",
    languages: ["English", "Kannada"],
    education: "BA LLB (Hons), National Law School",
    description: "Expert in civil litigation, property disputes, and real estate matters with a strong track record of successful cases."
  },
  {
    id: 3,
    name: "Adv. Mohammed Farooq",
    barRegistrationNo: "KBA/2008/9012",
    specialization: ["Family Law", "Civil Law"],
    experience: 15,
    location: "Mysore",
    court: "District Court, Mysore",
    phone: "+91 98452 34567",
    email: "mohammed.farooq@kbalaw.in",
    address: "78, Sayyaji Rao Road, Mysore - 570001",
    languages: ["English", "Kannada", "Urdu"],
    education: "LLB, Diploma in Family Law",
    description: "Compassionate approach to family law matters including divorce, custody, and matrimonial disputes."
  },
  {
    id: 4,
    name: "Adv. Lakshmi Venkatesh",
    barRegistrationNo: "KBA/2012/3456",
    specialization: ["Corporate Law", "Tax Law"],
    experience: 11,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98453 45678",
    email: "lakshmi.venkatesh@kbalaw.in",
    address: "201, Residency Road, Bangalore - 560025",
    languages: ["English", "Kannada", "Tamil"],
    education: "BBA LLB, LLM (Corporate Law)",
    description: "Specializes in corporate compliance, mergers & acquisitions, and taxation matters for businesses."
  },
  {
    id: 5,
    name: "Adv. Suresh Gowda",
    barRegistrationNo: "KBA/2003/7890",
    specialization: ["Criminal Law", "Labour Law"],
    experience: 20,
    location: "Mangalore",
    court: "District Court, Mangalore",
    phone: "+91 98454 56789",
    email: "suresh.gowda@kbalaw.in",
    address: "56, Balmatta Road, Mangalore - 575001",
    languages: ["English", "Kannada", "Tulu"],
    education: "LLB, PG Diploma in Labour Laws",
    description: "Veteran criminal lawyer with expertise in labour disputes and industrial relations."
  },
  {
    id: 6,
    name: "Adv. Anita Rao",
    barRegistrationNo: "KBA/2015/2345",
    specialization: ["Family Law", "Property Law"],
    experience: 8,
    location: "Hubli",
    court: "District Court, Hubli",
    phone: "+91 98455 67890",
    email: "anita.rao@kbalaw.in",
    address: "34, Station Road, Hubli - 580020",
    languages: ["English", "Kannada", "Marathi"],
    education: "BA LLB, Specialization in Family Law",
    description: "Dedicated to protecting family rights and resolving property inheritance disputes."
  },
  {
    id: 7,
    name: "Adv. Vikram Singh",
    barRegistrationNo: "KBA/2007/6789",
    specialization: ["Criminal Law", "Civil Law"],
    experience: 16,
    location: "Belgaum",
    court: "District Court, Belgaum",
    phone: "+91 98456 78901",
    email: "vikram.singh@kbalaw.in",
    address: "89, Tilakwadi, Belgaum - 590006",
    languages: ["English", "Kannada", "Hindi", "Marathi"],
    education: "LLB, LLM (Criminal Justice)",
    description: "Experienced in handling complex criminal cases and civil litigation matters."
  },
  {
    id: 8,
    name: "Adv. Deepa Nair",
    barRegistrationNo: "KBA/2014/4567",
    specialization: ["Corporate Law", "Constitutional Law"],
    experience: 9,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98457 89012",
    email: "deepa.nair@kbalaw.in",
    address: "112, Cunningham Road, Bangalore - 560052",
    languages: ["English", "Kannada", "Malayalam"],
    education: "BA LLB (Hons), LLM (Constitutional Law)",
    description: "Focuses on corporate governance, constitutional challenges, and public interest litigation."
  },
  {
    id: 9,
    name: "Adv. Ramesh Hegde",
    barRegistrationNo: "KBA/2006/8901",
    specialization: ["Property Law", "Civil Law"],
    experience: 17,
    location: "Mangalore",
    court: "Civil Court, Mangalore",
    phone: "+91 98458 90123",
    email: "ramesh.hegde@kbalaw.in",
    address: "67, Hampankatta, Mangalore - 575001",
    languages: ["English", "Kannada", "Konkani"],
    education: "LLB, Specialization in Property Law",
    description: "Expert in land acquisition, property registration, and real estate legal matters."
  },
  {
    id: 10,
    name: "Adv. Kavitha Reddy",
    barRegistrationNo: "KBA/2011/1122",
    specialization: ["Tax Law", "Corporate Law"],
    experience: 12,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98459 01234",
    email: "kavitha.reddy@kbalaw.in",
    address: "45, Lavelle Road, Bangalore - 560001",
    languages: ["English", "Kannada", "Telugu"],
    education: "B.Com LLB, LLM (Taxation)",
    description: "Specializes in GST, income tax litigation, and corporate tax planning."
  },
  {
    id: 11,
    name: "Adv. Arun Kumar",
    barRegistrationNo: "KBA/2009/3344",
    specialization: ["Labour Law", "Civil Law"],
    experience: 14,
    location: "Mysore",
    court: "Labour Court, Mysore",
    phone: "+91 98460 12345",
    email: "arun.kumar@kbalaw.in",
    address: "23, Irwin Road, Mysore - 570001",
    languages: ["English", "Kannada"],
    education: "LLB, Diploma in Labour & Industrial Laws",
    description: "Handles employment disputes, industrial relations, and labour compliance matters."
  },
  {
    id: 12,
    name: "Adv. Meera Bhat",
    barRegistrationNo: "KBA/2013/5566",
    specialization: ["Criminal Law", "Family Law"],
    experience: 10,
    location: "Hubli",
    court: "District Court, Hubli",
    phone: "+91 98461 23456",
    email: "meera.bhat@kbalaw.in",
    address: "78, Gokul Road, Hubli - 580030",
    languages: ["English", "Kannada", "Hindi"],
    education: "BA LLB, Specialization in Criminal Law",
    description: "Committed to defending the accused and handling sensitive family law cases."
  },
  {
    id: 13,
    name: "Adv. Sanjay Patil",
    barRegistrationNo: "KBA/2004/7788",
    specialization: ["Constitutional Law", "Civil Law"],
    experience: 19,
    location: "Belgaum",
    court: "High Court of Karnataka",
    phone: "+91 98462 34567",
    email: "sanjay.patil@kbalaw.in",
    address: "90, Club Road, Belgaum - 590001",
    languages: ["English", "Kannada", "Marathi"],
    education: "LLB, LLM (Constitutional Law), PhD",
    description: "Senior advocate specializing in constitutional matters and public interest litigation."
  },
  {
    id: 14,
    name: "Adv. Pooja Shetty",
    barRegistrationNo: "KBA/2016/9900",
    specialization: ["Property Law", "Family Law"],
    experience: 7,
    location: "Mangalore",
    court: "District Court, Mangalore",
    phone: "+91 98463 45678",
    email: "pooja.shetty@kbalaw.in",
    address: "12, Kadri Road, Mangalore - 575002",
    languages: ["English", "Kannada", "Tulu", "Konkani"],
    education: "BA LLB (Hons)",
    description: "Young and dynamic lawyer handling property disputes and family matters."
  },
  {
    id: 15,
    name: "Adv. Harish Gowda",
    barRegistrationNo: "KBA/2002/1357",
    specialization: ["Criminal Law", "Constitutional Law"],
    experience: 21,
    location: "Bangalore",
    court: "Supreme Court of India",
    phone: "+91 98464 56789",
    email: "harish.gowda@kbalaw.in",
    address: "156, Residency Road, Bangalore - 560025",
    languages: ["English", "Kannada", "Hindi"],
    education: "LLB, LLM, Senior Advocate",
    description: "Senior advocate practicing in Supreme Court with expertise in criminal and constitutional law."
  },
  {
    id: 16,
    name: "Adv. Nandini Iyer",
    barRegistrationNo: "KBA/2017/2468",
    specialization: ["Family Law", "Civil Law"],
    experience: 6,
    location: "Bangalore",
    court: "Family Court, Bangalore",
    phone: "+91 98465 67890",
    email: "nandini.iyer@kbalaw.in",
    address: "78, Indiranagar, Bangalore - 560038",
    languages: ["English", "Kannada", "Tamil", "Hindi"],
    education: "BA LLB (Hons), Specialization in Family Law",
    description: "Compassionate family law specialist handling divorce, custody, and domestic violence cases."
  },
  {
    id: 17,
    name: "Adv. Karthik Rao",
    barRegistrationNo: "KBA/2010/3579",
    specialization: ["Corporate Law", "Property Law"],
    experience: 13,
    location: "Mysore",
    court: "District Court, Mysore",
    phone: "+91 98466 78901",
    email: "karthik.rao@kbalaw.in",
    address: "45, Saraswathipuram, Mysore - 570009",
    languages: ["English", "Kannada"],
    education: "B.Com LLB, LLM (Corporate Law)",
    description: "Expert in corporate compliance, contract drafting, and commercial property transactions."
  },
  {
    id: 18,
    name: "Adv. Shweta Desai",
    barRegistrationNo: "KBA/2015/4680",
    specialization: ["Criminal Law", "Labour Law"],
    experience: 8,
    location: "Hubli",
    court: "District Court, Hubli",
    phone: "+91 98467 89012",
    email: "shweta.desai@kbalaw.in",
    address: "23, Vidyanagar, Hubli - 580021",
    languages: ["English", "Kannada", "Marathi"],
    education: "LLB, Diploma in Criminal Law",
    description: "Dedicated criminal defense lawyer with expertise in labour disputes and employee rights."
  },
  {
    id: 19,
    name: "Adv. Prakash Shetty",
    barRegistrationNo: "KBA/2008/5791",
    specialization: ["Tax Law", "Corporate Law"],
    experience: 15,
    location: "Mangalore",
    court: "High Court of Karnataka",
    phone: "+91 98468 90123",
    email: "prakash.shetty@kbalaw.in",
    address: "67, Kodialbail, Mangalore - 575003",
    languages: ["English", "Kannada", "Tulu", "Konkani"],
    education: "B.Com LLB, LLM (Taxation), CA",
    description: "Chartered Accountant and lawyer specializing in tax litigation and corporate taxation."
  },
  {
    id: 20,
    name: "Adv. Divya Murthy",
    barRegistrationNo: "KBA/2014/6802",
    specialization: ["Property Law", "Civil Law"],
    experience: 9,
    location: "Belgaum",
    court: "Civil Court, Belgaum",
    phone: "+91 98469 01234",
    email: "divya.murthy@kbalaw.in",
    address: "89, Khanapur Road, Belgaum - 590003",
    languages: ["English", "Kannada", "Marathi"],
    education: "BA LLB, Specialization in Property Law",
    description: "Specializes in property disputes, land acquisition, and real estate documentation."
  },
  {
    id: 21,
    name: "Adv. Arjun Kulkarni",
    barRegistrationNo: "KBA/2011/7913",
    specialization: ["Constitutional Law", "Criminal Law"],
    experience: 12,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98470 12345",
    email: "arjun.kulkarni@kbalaw.in",
    address: "34, Jayanagar, Bangalore - 560041",
    languages: ["English", "Kannada", "Hindi"],
    education: "BA LLB (Hons), LLM (Constitutional Law)",
    description: "Handles constitutional challenges, public interest litigation, and criminal appeals."
  },
  {
    id: 22,
    name: "Adv. Sneha Prabhu",
    barRegistrationNo: "KBA/2016/8024",
    specialization: ["Family Law", "Property Law"],
    experience: 7,
    location: "Mysore",
    court: "Family Court, Mysore",
    phone: "+91 98471 23456",
    email: "sneha.prabhu@kbalaw.in",
    address: "56, Vijayanagar, Mysore - 570017",
    languages: ["English", "Kannada", "Tamil"],
    education: "BA LLB, Specialization in Family Law",
    description: "Empathetic approach to family matters and property inheritance disputes."
  },
  {
    id: 23,
    name: "Adv. Ravi Shankar",
    barRegistrationNo: "KBA/2005/9135",
    specialization: ["Labour Law", "Civil Law"],
    experience: 18,
    location: "Hubli",
    court: "Labour Court, Hubli",
    phone: "+91 98472 34567",
    email: "ravi.shankar@kbalaw.in",
    address: "12, Unkal, Hubli - 580031",
    languages: ["English", "Kannada", "Hindi"],
    education: "LLB, LLM (Labour Laws)",
    description: "Veteran labour law expert handling industrial disputes and employment matters."
  },
  {
    id: 24,
    name: "Adv. Pallavi Joshi",
    barRegistrationNo: "KBA/2013/0246",
    specialization: ["Corporate Law", "Tax Law"],
    experience: 10,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98473 45678",
    email: "pallavi.joshi@kbalaw.in",
    address: "90, Koramangala, Bangalore - 560034",
    languages: ["English", "Kannada", "Hindi"],
    education: "B.Com LLB (Hons), LLM (Corporate Law)",
    description: "Corporate legal advisor specializing in startup law, compliance, and taxation."
  },
  {
    id: 25,
    name: "Adv. Ganesh Bhat",
    barRegistrationNo: "KBA/2009/1357",
    specialization: ["Criminal Law", "Civil Law"],
    experience: 14,
    location: "Mangalore",
    court: "District Court, Mangalore",
    phone: "+91 98474 56789",
    email: "ganesh.bhat@kbalaw.in",
    address: "45, Bejai, Mangalore - 575004",
    languages: ["English", "Kannada", "Tulu", "Konkani"],
    education: "LLB, LLM (Criminal Law)",
    description: "Experienced in criminal defense and civil litigation with strong courtroom presence."
  },
  {
    id: 26,
    name: "Adv. Sowmya Reddy",
    barRegistrationNo: "KBA/2018/2468",
    specialization: ["Family Law", "Constitutional Law"],
    experience: 5,
    location: "Belgaum",
    court: "District Court, Belgaum",
    phone: "+91 98475 67890",
    email: "sowmya.reddy@kbalaw.in",
    address: "23, Angol, Belgaum - 590006",
    languages: ["English", "Kannada", "Marathi", "Telugu"],
    education: "BA LLB (Hons), National Law School",
    description: "Young advocate passionate about women's rights and constitutional matters."
  },
  {
    id: 27,
    name: "Adv. Mahesh Kumar",
    barRegistrationNo: "KBA/2007/3579",
    specialization: ["Property Law", "Tax Law"],
    experience: 16,
    location: "Bangalore",
    court: "Civil Court, Bangalore",
    phone: "+91 98476 78901",
    email: "mahesh.kumar@kbalaw.in",
    address: "67, Malleshwaram, Bangalore - 560003",
    languages: ["English", "Kannada", "Hindi"],
    education: "LLB, LLM (Property Law)",
    description: "Expert in property transactions, title verification, and property tax matters."
  },
  {
    id: 28,
    name: "Adv. Rekha Shenoy",
    barRegistrationNo: "KBA/2012/4680",
    specialization: ["Criminal Law", "Family Law"],
    experience: 11,
    location: "Mysore",
    court: "District Court, Mysore",
    phone: "+91 98477 89012",
    email: "rekha.shenoy@kbalaw.in",
    address: "89, Kuvempunagar, Mysore - 570023",
    languages: ["English", "Kannada", "Tulu"],
    education: "BA LLB, Specialization in Criminal Law",
    description: "Strong advocate for victims' rights in criminal and family law cases."
  },
  {
    id: 29,
    name: "Adv. Naveen Gowda",
    barRegistrationNo: "KBA/2010/5791",
    specialization: ["Labour Law", "Corporate Law"],
    experience: 13,
    location: "Hubli",
    court: "Labour Court, Hubli",
    phone: "+91 98478 90123",
    email: "naveen.gowda@kbalaw.in",
    address: "34, Navanagar, Hubli - 580025",
    languages: ["English", "Kannada", "Hindi"],
    education: "LLB, LLM (Labour & Corporate Law)",
    description: "Handles employment contracts, labour disputes, and corporate HR matters."
  },
  {
    id: 30,
    name: "Adv. Suma Hegde",
    barRegistrationNo: "KBA/2015/6802",
    specialization: ["Civil Law", "Property Law"],
    experience: 8,
    location: "Mangalore",
    court: "Civil Court, Mangalore",
    phone: "+91 98479 01234",
    email: "suma.hegde@kbalaw.in",
    address: "56, Kankanady, Mangalore - 575002",
    languages: ["English", "Kannada", "Tulu", "Konkani"],
    education: "BA LLB, Specialization in Civil Law",
    description: "Specializes in civil suits, property disputes, and contract enforcement."
  },
  {
    id: 31,
    name: "Adv. Ashok Patil",
    barRegistrationNo: "KBA/2006/7913",
    specialization: ["Constitutional Law", "Tax Law"],
    experience: 17,
    location: "Belgaum",
    court: "High Court of Karnataka",
    phone: "+91 98480 12345",
    email: "ashok.patil@kbalaw.in",
    address: "78, Camp, Belgaum - 590001",
    languages: ["English", "Kannada", "Marathi", "Hindi"],
    education: "LLB, LLM (Constitutional Law), PhD",
    description: "Senior advocate specializing in constitutional law and tax litigation at High Court level."
  },
  {
    id: 32,
    name: "Adv. Vidya Rao",
    barRegistrationNo: "KBA/2014/8024",
    specialization: ["Family Law", "Civil Law"],
    experience: 9,
    location: "Bangalore",
    court: "Family Court, Bangalore",
    phone: "+91 98481 23456",
    email: "vidya.rao@kbalaw.in",
    address: "90, Basavanagudi, Bangalore - 560004",
    languages: ["English", "Kannada", "Tamil", "Telugu"],
    education: "BA LLB (Hons), Specialization in Family Law",
    description: "Dedicated to resolving family disputes through mediation and litigation."
  },
  {
    id: 33,
    name: "Adv. Sunil Kamath",
    barRegistrationNo: "KBA/2011/9135",
    specialization: ["Criminal Law", "Property Law"],
    experience: 12,
    location: "Mysore",
    court: "District Court, Mysore",
    phone: "+91 98482 34567",
    email: "sunil.kamath@kbalaw.in",
    address: "12, Gokulam, Mysore - 570002",
    languages: ["English", "Kannada", "Tulu"],
    education: "LLB, LLM (Criminal Law)",
    description: "Experienced criminal lawyer also handling property-related criminal cases."
  },
  {
    id: 34,
    name: "Adv. Jyoti Kulkarni",
    barRegistrationNo: "KBA/2017/0246",
    specialization: ["Corporate Law", "Labour Law"],
    experience: 6,
    location: "Hubli",
    court: "District Court, Hubli",
    phone: "+91 98483 45678",
    email: "jyoti.kulkarni@kbalaw.in",
    address: "45, Gokul Road, Hubli - 580030",
    languages: ["English", "Kannada", "Marathi"],
    education: "BBA LLB, Specialization in Corporate Law",
    description: "Corporate lawyer focusing on startup legal matters and employment law."
  },
  {
    id: 35,
    name: "Adv. Raghavendra Rao",
    barRegistrationNo: "KBA/2008/1357",
    specialization: ["Tax Law", "Civil Law"],
    experience: 15,
    location: "Mangalore",
    court: "High Court of Karnataka",
    phone: "+91 98484 56789",
    email: "raghavendra.rao@kbalaw.in",
    address: "67, Pandeshwar, Mangalore - 575001",
    languages: ["English", "Kannada", "Tulu", "Hindi"],
    education: "B.Com LLB, LLM (Taxation)",
    description: "Tax litigation expert handling GST, income tax, and customs matters."
  },
  {
    id: 36,
    name: "Adv. Latha Srinivas",
    barRegistrationNo: "KBA/2013/2468",
    specialization: ["Family Law", "Property Law"],
    experience: 10,
    location: "Belgaum",
    court: "Family Court, Belgaum",
    phone: "+91 98485 67890",
    email: "latha.srinivas@kbalaw.in",
    address: "89, Shahapur, Belgaum - 590003",
    languages: ["English", "Kannada", "Marathi", "Hindi"],
    education: "BA LLB, Specialization in Family Law",
    description: "Compassionate family lawyer handling divorce, custody, and property settlements."
  },
  {
    id: 37,
    name: "Adv. Mohan Das",
    barRegistrationNo: "KBA/2009/3579",
    specialization: ["Criminal Law", "Constitutional Law"],
    experience: 14,
    location: "Bangalore",
    court: "High Court of Karnataka",
    phone: "+91 98486 78901",
    email: "mohan.das@kbalaw.in",
    address: "23, Rajajinagar, Bangalore - 560010",
    languages: ["English", "Kannada", "Hindi", "Tamil"],
    education: "LLB, LLM (Criminal & Constitutional Law)",
    description: "Senior criminal lawyer with expertise in constitutional challenges and appeals."
  },
  {
    id: 38,
    name: "Adv. Savitha Nair",
    barRegistrationNo: "KBA/2016/4680",
    specialization: ["Labour Law", "Civil Law"],
    experience: 7,
    location: "Mysore",
    court: "Labour Court, Mysore",
    phone: "+91 98487 89012",
    email: "savitha.nair@kbalaw.in",
    address: "56, Hebbal, Mysore - 570016",
    languages: ["English", "Kannada", "Malayalam"],
    education: "LLB, Diploma in Labour Laws",
    description: "Advocates for employee rights and handles industrial disputes."
  },
  {
    id: 39,
    name: "Adv. Prasad Shetty",
    barRegistrationNo: "KBA/2012/5791",
    specialization: ["Corporate Law", "Property Law"],
    experience: 11,
    location: "Hubli",
    court: "District Court, Hubli",
    phone: "+91 98488 90123",
    email: "prasad.shetty@kbalaw.in",
    address: "34, Deshpande Nagar, Hubli - 580029",
    languages: ["English", "Kannada", "Marathi"],
    education: "B.Com LLB, LLM (Corporate Law)",
    description: "Corporate and property law expert for businesses and real estate developers."
  },
  {
    id: 40,
    name: "Adv. Manjula Hegde",
    barRegistrationNo: "KBA/2010/6802",
    specialization: ["Civil Law", "Tax Law"],
    experience: 13,
    location: "Mangalore",
    court: "Civil Court, Mangalore",
    phone: "+91 98489 01234",
    email: "manjula.hegde@kbalaw.in",
    address: "78, Surathkal, Mangalore - 575014",
    languages: ["English", "Kannada", "Tulu", "Konkani"],
    education: "BA LLB, LLM (Civil & Tax Law)",
    description: "Handles civil litigation and tax-related disputes for individuals and businesses."
  }
];

const specializations = [
  "All Specializations",
  "Criminal Law",
  "Civil Law",
  "Family Law",
  "Corporate Law",
  "Property Law",
  "Tax Law",
  "Labour Law",
  "Constitutional Law"
];

const locations = [
  "All Locations",
  "Bangalore",
  "Mysore",
  "Mangalore",
  "Hubli",
  "Belgaum"
];

module.exports = {
  lawyersData,
  specializations,
  locations
};
